### ISSUE TITLE
Extension updates .vscode/settings.json every two seconds

### ISSUE THREAD

**Issue by entepe85** [sadesyllas/explorer-excluded-files#1]
Since the only entries in that file are generated by explorer-excluded-file I presume that this extension is regenerating that file periodically, but way too often.

**Comment by sadesyllas** [comment]
The extension should not be writing to the file if nothing has changed since the first time it wrote to it. Is the file being manually removed? It's true that it needs optimization as to when the settings file is updated but it should not actually write anything to the file if nothing has changed.

**Comment by entepe85** [comment]
Thanks for pointing that out. I kept an eye on when the file gets refreshed/rewritten but it was not obvious to me that anything else interfered with it, such as automatic deletion or similar.

**Comment by sadesyllas** [comment]
I am closing this issue since it's become very old and no updates have been posted.
If there is still a problem with the extension please re-open it.

Thanks

**Comment by mherger** [comment]
@entepe85 - IMHO this problem still persists (or is back again): my .vscode/settings.json file is updated every 5s, even if nothing has changed. Reading might be okish, but writing isn't good. I store my code and vscode configuration on Dropbox. Due to this issue Dropbox is constantly busy verifying the un-altered settings.json file.

Additionally it seems to trigger the git monitor. When your plugin is enabled I see vscode git update every five seconds. If I disable it, that polling is gone, too.

**Comment by mherger** [comment]
I think one of the issues is that the `workstationConfiguration` is set to use some defaults (eg. https://github.com/sadesyllas/explorer-excluded-files/blob/5e5a693f3995a113fb4122627349b1c2ab5b6c1e/src/extension.ts#L217), whereas the `workspaceConfigurationText` is not. Which means that the former would become `{files.exclude:{}}` by default, but `workspaceConfigurationText` would stay `{}` - causing the re-build of the file when no exclusion is defined in a project.
